server:
  port: 8888
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1KB
  http2:
    enabled: true
spring:
  application:
    name: gateway-dynamic-demo
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 30
        max-idle: 10
        max-wait: -1ms
        min-idle: 0
      shutdownTimeout: 100ms
    password: gatewayredis123
    port: 6666
    timeout: 100ms
  data:
    mongodb:
      uri: mongodb://gateway:123456@127.0.0.1:7777/gateway
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: ${ADDITIONAL_EUREKA_SERVER_LIST:http://192.168.1.177:8880/eureka/}
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
logging:
  level:
    com:
      demon: debug
    org: warn
    root: info
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} ${spring.application.name} [%thread] %-5level %logger{50} - %msg%n'

ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 6000